README.md
docs/meetings.md
docs/meetings_2020.md

Setup the README with the content from the workstream README, the
charter and some more.
Archive meeting minutes to meetings_2020.

Initial content for the SIG events docs

---

vocabulary-draft/introduction.md

This is just the introduction section, so we can add comments here about the changes. 
We can link also to a github discussion thread in this issue.

Introduction to Vocabulary PR

---

vocabulary-draft/source-code-version-control.md

PR to discuss Source code version control Events

Source Code Version Control Events section

---

vocabulary-draft/continuous-integration-pipeline-events.md

PR to discuss CI pipeline events.

Continuous Integration pipeline events section

---

vocabulary-draft/continuous-deployment-pipeline-events.md

PR to discuss Continuous Deployment pipelines events

Continuous Deployment pipelines events section

---

vocabulary-draft/continuous-delivery.md

- Moved Pipeline and Task events from CI PR to CD

Continuous Delivery bucket for events

---

vocabulary-draft/source-code-version-control.md

For source code versioning events related to #45

Remote bucket from Event Type

---

vocabulary-draft/core.md

For core events related to #45

Remove buckets from event types

---

vocabulary-draft/continuous-integration-pipeline-events.md

remove bucket from event type

---

vocabulary-draft/continuous-deployment-pipeline-events.md

For env and services events related to #45

remove bucket from environment and service events types

---

poc/README.md

Add a PoC README

---

cde/sdk/go/pkg/cdf/events/event_types.go

Another simple PR to start fixing things .. one event at the time.. I want to make sure that I can emit an event from a client producer and read events in a client consumer with the library as it is intended to be used. Once the roundtrip is done, I will start adding tests and removing code duplication.

Fixing typo and using constants

---

poc/README.md

Note: Text below diagram refers to the updated diagram, not the one currently in the repo.
The text contains some TODO's, please help fill those in if you have more info.

Add PoC details to README.md

---

poc/tekton/0003_triggers.yaml
poc/tekton/0004_pipelines.yaml

Add the deploy pipeline

---

poc/docker/Dockerfile

Fix image name in docker file

---

cde/sdk/go/pkg/cdf/events/extensions/service_extension.go

add service extension

---

README.md
vocabulary-draft/README.md
vocabulary-draft/introduction.md

Add a README to the vocabulary-draft folder.
Add links from the main README to the vacabulary, sdk and poc folders.
Add notes about lightweight events, as agreed in https://github.com/cdfoundation/sig-events/discussions/47

Protocol README and size recommendation

---

poc/poc.sh

This PR makes it easier to find the required repo and programs needed by the POC and also check if they can be found.
- Add the location of inbound and outbound adapters are found
- Add the location of tektoncd experimental
- Add Links to required programs
- Add checks for need repos and commands
Signed-off-by: Mattias Linnér mattias.linner@ericsson.com

Improve poc.sh

---

poc/docker/index.html
poc/poc.sh

Remove keptn patches as they are already included in the latest versions

Keptn patches

---

cde/sdk/go/README.md

Made some minor changes to copy and paste mistakes:
* Fixed some inconsistencies between the description text and the examples.
* Now all events that have queued, started, finished have the same order
Signed of by: Mattias Linnér mattias.linner@ericsson.com

Fixing inconsistencies in readme

---

README.md
vocabulary-draft/README.md

Add and update some parts of the README's to declare how the work towards a common events specification through CDEvents can be followed.

Update basic info and links to CDEvents

---

docs/SIG Meeting Notes 2022.md

Restore the SIG Events meeting notes 2022

---

README.md

Add @agardnerit as member

---

README.md

And updates the README to link to artifacts on CDEvents side.

Update the meetings schedule
